from __future__ import annotations

# ruff: noqa: F401,I001,E501

from typing import Any, Mapping, Protocol

from typing_extensions import TypeAlias

from openrouter._hooks import (
    AfterErrorContext,
    AfterErrorHook,
    AfterSuccessContext,
    AfterSuccessHook,
    BeforeRequestContext,
    BeforeRequestHook,
    HookContext,
    SDKHooks,
    SDKInitHook,
)
from openrouter.components import (
    BaseInputsUnion,
    ChatAssistantMessage,
    ChatMessages,
    EasyInputMessage,
    EasyInputMessageContentInputImage,
    EasyInputMessageContentUnion1,
    EasyInputMessageRoleUnion,
    ErrorEvent,
    FunctionCallItem,
    FunctionCallOutputItem,
    InputAudio,
    InputFile,
    InputImage,
    InputMessageItem,
    InputsUnion,
    InputText,
    InputVideo,
    OpenAIResponsesToolChoiceUnion,
    OpenResponsesResult,
    OutputFileSearchCallItem,
    OutputFunctionCallItem,
    OutputImage,
    OutputImageGenerationCallItem,
    OutputItems,
    OutputMessage,
    OutputReasoningItem,
    OutputWebSearchCallItem,
    ResponseOutputText,
    ResponsesRequest,
    ResponsesRequestToolUnion,
    StreamEvents,
    Usage,
)

from .anthropic_compat import from_claude_messages, to_claude_message
from .async_params import (
    CallModelInput,
    CallModelInputWithState,
    ResolvedCallModelInput,
    has_async_functions,
    resolve_async_functions,
)
from .call_model import call_model
from .chat_compat import from_chat_messages, to_chat_message
from .claude_constants import ClaudeContentBlockType, NonClaudeMessageRole
from .claude_type_guards import is_claude_style_messages
from .conversation_state import (
    CONVERSATION_STATE_VERSION,
    InvalidStateError,
    UnsupportedStateVersionError,
    append_to_messages,
    create_initial_state,
    create_rejected_result,
    create_unsent_result,
    deserialize_conversation_state,
    generate_conversation_id,
    partition_tool_calls,
    serialize_conversation_state,
    tool_requires_approval,
    update_state,
)
from .hooks_manager import HooksManager
from .hooks_schemas import (
    HookDefinition,
    HookName,
    HookRegistry,
    ModelCallUsage,
    PermissionRequestPayload,
    PermissionRequestResult,
    PostModelCallPayload,
    PostToolUseFailurePayload,
    PostToolUsePayload,
    PreToolUsePayload,
    PreToolUseResult,
    SessionEndPayload,
    SessionStartPayload,
    SessionUsageTotals,
    StopPayload,
    StopResult,
    UserPromptSubmitPayload,
    UserPromptSubmitResult,
)
from .hooks_types import (
    DEFAULT_ASYNC_TIMEOUT_MS,
    HOOK_BEHAVIOR,
    AsyncOutput,
    EmitResult,
    HookBehavior,
    HookEntry,
    HookHandler,
    InlineHookConfig,
    LifecycleHookContext,
    ToolMatcher,
    is_async_output,
)
from .item_types import (
    AssistantMessageItem,
    CallFileSearchItem,
    CallFunctionToolItem,
    CallImageGenerationItem,
    CallWebSearchItem,
    DeveloperMessageItem,
    ErrorItem,
    FunctionProgressItem,
    FunctionResultItem,
    Item,
    NewUserMessageItem,
    ReasoningItem,
    SystemMessageItem,
    UserMessageItem,
)
from .model_result import DEFAULT_FINAL_RESPONSE_DIRECTIVE, GetResponseOptions, ModelResult
from .next_turn_params import (
    apply_next_turn_params_to_request,
    build_next_turn_params_context,
    execute_next_turn_params_functions,
)
from .openrouter import Hook, OpenRouter, OpenRouterOptions, SDKOptions
from .stop_conditions import (
    finish_reason_is,
    has_tool_call,
    is_stop_condition_met,
    max_cost,
    max_tokens_used,
    step_count_is,
)
from .stream_transformers import (
    StreamableOutputItem,
    extract_unsupported_content,
    get_unsupported_content_summary,
    has_unsupported_content,
)
from .tool import mark_mcp, server_tool, tool
from .tool_context import ContextInput, ToolContextStore, build_tool_execute_context
from .tool_event_broadcaster import ToolEventBroadcaster
from .tool_types import (
    ChatStreamEvent,
    ClientTool,
    ConversationState,
    ConversationStatus,
    EnhancedResponseStreamEvent,
    HITLTool,
    HITLToolFunction,
    HasApprovalTools,
    InferToolEvent,
    InferToolEventsUnion,
    InferToolInput,
    InferToolOutput,
    InferToolOutputsUnion,
    ManualTool,
    McpBranded,
    NextTurnParamsContext,
    NextTurnParamsFunctions,
    ParsedToolCall,
    PartialResponse,
    ResponseStreamEvent,
    ServerTool,
    ServerToolConfig,
    ServerToolResultItem,
    ServerToolType,
    StateAccessor,
    StepResult,
    StopCondition,
    StopWhen,
    ToModelOutputFunction,
    ToModelOutputResult,
    Tool,
    ToolApprovalCheck,
    ToolCallOutputEvent,
    ToolExecutionResult,
    ToolExecutionResultUnion,
    ToolHasApproval,
    ToolOutputContentItem,
    ToolPreliminaryResultEvent,
    ToolResultEvent,
    ToolResultItem,
    ToolStreamEvent,
    ToolType,
    ToolWithExecute,
    ToolWithGenerator,
    TurnContext,
    TurnEndEvent,
    TurnStartEvent,
    TypedToolCall,
    TypedToolCallUnion,
    UnsentToolResult,
    Warning,
    has_approval_required_tools,
    has_execute_function,
    is_auto_resolvable_tool,
    is_client_tool,
    is_generator_tool,
    is_hitl_tool,
    is_manual_tool,
    is_mcp_tool,
    is_regular_execute_tool,
    is_server_tool,
    is_tool_call_output_event,
    is_tool_preliminary_result_event,
    is_tool_result_event,
    is_turn_end_event,
    is_turn_start_event,
    tool_has_approval_configured,
)
from .turn_context import build_turn_context, normalize_input_to_array

RequestOptions: TypeAlias = Mapping[str, Any]


class BeforeCreateRequestContext(Protocol):
    operation_id: str


class BeforeCreateRequestHook(Protocol):
    def before_create_request(self, hook_ctx: BeforeCreateRequestContext, request: Any) -> Any: ...


OutputInputImage = OutputImage

__all__ = [
    "AfterErrorContext",
    "AfterErrorHook",
    "AfterSuccessContext",
    "AfterSuccessHook",
    "AssistantMessageItem",
    "AsyncOutput",
    "BaseInputsUnion",
    "BeforeCreateRequestContext",
    "BeforeCreateRequestHook",
    "BeforeRequestContext",
    "BeforeRequestHook",
    "CONVERSATION_STATE_VERSION",
    "CallFileSearchItem",
    "CallFunctionToolItem",
    "CallImageGenerationItem",
    "CallModelInput",
    "CallModelInputWithState",
    "CallWebSearchItem",
    "ChatAssistantMessage",
    "ChatMessages",
    "ChatStreamEvent",
    "ClaudeContentBlockType",
    "ClientTool",
    "ConversationState",
    "ConversationStatus",
    "DEFAULT_ASYNC_TIMEOUT_MS",
    "DEFAULT_FINAL_RESPONSE_DIRECTIVE",
    "DeveloperMessageItem",
    "EasyInputMessage",
    "EasyInputMessageContentInputImage",
    "EasyInputMessageContentUnion1",
    "EasyInputMessageRoleUnion",
    "EmitResult",
    "EnhancedResponseStreamEvent",
    "ErrorEvent",
    "ErrorItem",
    "FunctionCallItem",
    "FunctionCallOutputItem",
    "FunctionProgressItem",
    "FunctionResultItem",
    "GetResponseOptions",
    "HITLTool",
    "HITLToolFunction",
    "HOOK_BEHAVIOR",
    "HasApprovalTools",
    "Hook",
    "HookBehavior",
    "HookContext",
    "HookDefinition",
    "HookEntry",
    "HookHandler",
    "HookName",
    "HookRegistry",
    "HooksManager",
    "InferToolEvent",
    "InferToolEventsUnion",
    "InferToolInput",
    "InferToolOutput",
    "InferToolOutputsUnion",
    "InlineHookConfig",
    "InputAudio",
    "InputFile",
    "InputImage",
    "InputMessageItem",
    "InputText",
    "InputVideo",
    "InputsUnion",
    "InvalidStateError",
    "Item",
    "LifecycleHookContext",
    "ManualTool",
    "McpBranded",
    "ModelCallUsage",
    "ModelResult",
    "NewUserMessageItem",
    "NextTurnParamsContext",
    "NextTurnParamsFunctions",
    "NonClaudeMessageRole",
    "OpenAIResponsesToolChoiceUnion",
    "OpenResponsesResult",
    "OpenRouter",
    "OpenRouterOptions",
    "OutputFileSearchCallItem",
    "OutputFunctionCallItem",
    "OutputImage",
    "OutputImageGenerationCallItem",
    "OutputInputImage",
    "OutputItems",
    "OutputMessage",
    "OutputReasoningItem",
    "OutputWebSearchCallItem",
    "ParsedToolCall",
    "PartialResponse",
    "PermissionRequestPayload",
    "PermissionRequestResult",
    "PostModelCallPayload",
    "PostToolUseFailurePayload",
    "PostToolUsePayload",
    "PreToolUsePayload",
    "PreToolUseResult",
    "ReasoningItem",
    "RequestOptions",
    "ResolvedCallModelInput",
    "ResponseOutputText",
    "ResponseStreamEvent",
    "ResponsesRequest",
    "ResponsesRequestToolUnion",
    "SDKHooks",
    "SDKInitHook",
    "SDKOptions",
    "ServerTool",
    "ServerToolConfig",
    "ServerToolResultItem",
    "ServerToolType",
    "SessionEndPayload",
    "SessionStartPayload",
    "SessionUsageTotals",
    "StateAccessor",
    "StepResult",
    "StopCondition",
    "StopPayload",
    "StopResult",
    "StopWhen",
    "StreamEvents",
    "StreamableOutputItem",
    "SystemMessageItem",
    "ToModelOutputFunction",
    "ToModelOutputResult",
    "Tool",
    "ToolApprovalCheck",
    "ToolCallOutputEvent",
    "ToolContextStore",
    "ToolEventBroadcaster",
    "ToolExecutionResult",
    "ToolExecutionResultUnion",
    "ToolHasApproval",
    "ToolMatcher",
    "ToolOutputContentItem",
    "ToolPreliminaryResultEvent",
    "ToolResultEvent",
    "ToolResultItem",
    "ToolStreamEvent",
    "ToolType",
    "ToolWithExecute",
    "ToolWithGenerator",
    "TurnContext",
    "TurnEndEvent",
    "TurnStartEvent",
    "TypedToolCall",
    "TypedToolCallUnion",
    "UnsentToolResult",
    "UnsupportedStateVersionError",
    "Usage",
    "UserMessageItem",
    "UserPromptSubmitPayload",
    "UserPromptSubmitResult",
    "Warning",
    "append_to_messages",
    "apply_next_turn_params_to_request",
    "build_next_turn_params_context",
    "build_tool_execute_context",
    "build_turn_context",
    "call_model",
    "create_initial_state",
    "create_rejected_result",
    "create_unsent_result",
    "deserialize_conversation_state",
    "execute_next_turn_params_functions",
    "extract_unsupported_content",
    "finish_reason_is",
    "from_chat_messages",
    "from_claude_messages",
    "generate_conversation_id",
    "get_unsupported_content_summary",
    "has_approval_required_tools",
    "has_async_functions",
    "has_execute_function",
    "has_tool_call",
    "has_unsupported_content",
    "is_async_output",
    "is_auto_resolvable_tool",
    "is_client_tool",
    "is_claude_style_messages",
    "is_generator_tool",
    "is_hitl_tool",
    "is_manual_tool",
    "is_mcp_tool",
    "is_regular_execute_tool",
    "is_server_tool",
    "is_stop_condition_met",
    "is_tool_call_output_event",
    "is_tool_preliminary_result_event",
    "is_tool_result_event",
    "is_turn_end_event",
    "is_turn_start_event",
    "mark_mcp",
    "max_cost",
    "max_tokens_used",
    "normalize_input_to_array",
    "partition_tool_calls",
    "resolve_async_functions",
    "serialize_conversation_state",
    "server_tool",
    "step_count_is",
    "to_chat_message",
    "to_claude_message",
    "tool",
    "tool_has_approval_configured",
    "tool_requires_approval",
    "update_state",
]
